txd = engineLoadTXD("hotdog.txd")
engineImportTXD(txd,588)
dff = engineLoadDFF("hotdog.dff", 588)
engineReplaceModel(dff, 588)
txd = engineLoadTXD("journey.txd")
engineImportTXD(txd,508)
dff = engineLoadDFF("journey.dff", 508)
engineReplaceModel(dff, 508)
txd = engineLoadTXD("newsvan.txd", 582)
engineImportTXD(txd, 582)